### ISSUE TITLE
Record who uses the template

### ISSUE THREAD

**Issue by myoungerman** [dorrzun/TemplateMaker#30]
Store the user's name, the current date, and the document name in either Google Sheets or Firebase so I can retrieve it to create a graph that shows how many people are using the template.

**Comment by myoungerman** [comment]
I decided to use Firebase because I don't see a way to pass information directly from Google Docs to Google Sheets.

How will this work?
1.  When a user adds title page information to their copy of the template, their name, the date, and the document name will be stored in the Google Sheet in the Test Plan Template folder.
2. A button in the Google Sheet will pull that data into the spreadsheet and place it in the correct columns. The button will then create a chart (either a bar graph or pie chart) based off that data. I'll need to talk with Jerald to see how he wants to be able to filter the data.

**Comment by VerumEmanio** [comment]
I'm now able to pass the data into the spreadsheet, but
